config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'projects'=> 'static_pages#projects'
  get 'resume'=> 'static_pages#resume'
  get 'contact'=> 'static_pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end
  
  def resume
  end
  
  def contact
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Taylor Wisler"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "Taylor", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav pull-right">
        <li><%= link_to "Home",    root_path, id:"LinkColor"%></li>
        <li><%= link_to "Projects",    projects_path, id:"LinkColor" %></li>
        <li><%= link_to "Resume",    resume_path, id:"LinkColor" %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>

<div class="row">

</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Taylor Wisler</h1>
  
  <div id="cont" class="container">
  
    <div id = "middle_left" class="container">
      <%= image_tag("profMe.jpg", id: "me") %>
    </div>
    
    <div id = "middle_right" class="container">
    
      <h2>Biography</h2> 
      
      <p >
      My name is Taylor Wisler, and I currently attend 
      <a href="http://trine.edu/">Trine University</a>
       studying as a senior Computer Engineer. Throughout my time here I have completed many projects, for school and on my own.
       I have compiled this website as a way to host and display all of my open source projects for anyone to see. 
      </p>
      
    </div>
    
    <div style="clear: both;"></div>
    
  </div>
  <div id="facebookLink">
    <a href="https://www.linkedin.com/profile/view?id=274294364&trk=nav_responsive_tab_profile">My LinkedIn</a>
  </div>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, "Projects") %>
<div >

  <h1>Projects</h1>
  
   <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Senior Design Project</h2>
      <p id="ResumeParagraphs">
          My senior design group of 5 people developed a smart power, or alternative energy system. The system would
          use a solar panel to charge a 12v car battery, and then be able to power typical household appliances such as
          phone chargers or lamps. On the user interface side of things, the user is able to control the system with a
          simple android application. The user is able to turn on or off three seperate loads, change between the battery
          supply or the grid power, and check the current charge of the battery via a graph. The other 4 students were
          electrical engineers, so my portion of the project was the entire software end.<br><br>
          
          The way that I decided to handle the system was by dividing the project into three parts that communicated
          using HTTP requests. The three parts were an android application that the users interfaced with, a Ruby on Rails
          website that was used as a median, and a Python script on a Raspberry Pi that physically controlled the loads and
          read from the battery. Here is a simple block diagram of the system:<br>
          
      
          <%= image_tag("SeniorDesignBlockDiagram.png") %>
          <br>
      
      
          The code for my Rails website is in
          <a href="https://ide.c9.io/tawisler11/senior_design">this workspace.</a><br>
          
          This is the bitbucket repository for the 
          <a href="https://bitbucket.org/tawisler11/senior_design_android_app">Android application.</a><br>
          
          This is the bitbucket repository for the 
          <a href="https://bitbucket.org/tawisler11/senior_design_raspberrypi_python">Raspberry Pi script.</a>
          
          
      </p>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Ruby on Rails Personal Website</h2>
      <p id="ResumeParagraphs">
          This website was developed on the 
          <a href="https://c9.io/">Cloud9</a>
           development environment, using Ruby on Rails.<br>
           My 
           <a href="https://ide.c9.io/tawisler11/taylor">workspace</a>
            is public, and is free for anyone to view.
      </p>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Light Organ Project</h2>
      <p id="ResumeParagraphs">
          The Light Organ Project was more of a hobby project that I developed. Some of my friends and I had bought some LED light strips that came with preset
          functionality, and I decided that I could make much more enjoyable modes. I made a small arduino project that could control those LED strips and 
          flash along with my music.<br><br>
          The full arduino code, as well as a schematic of my circuitry can be viewed on my bitbucket
          <a href="https://bitbucket.org/tawisler11/light_organ">Light Organ repository</a>
          in the file /NEW_LED/NEW_LED.ino.
      </p>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Zen Alarm Clock Project</h2>
      <p id="ResumeParagraphs">
          The zen alarm clock was a project for a class where I worked with 3 other team mates. The alarm clock consisted of input buttons, a HD44780 display for the interface and time display, 
          a high power LED that gets progressively brighter, and a buzzer that gets progressively louder.<br><br>
          This project was written in C, and uses queues that we created
          using structs. The program is also structured in a task based system.<br><br>
          The code can be viewed on my bitbucket
          <a href="https://bitbucket.org/tawisler11/light_organ">Zen Alarm Clock Project repository</a>
      </p>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Pong Game</h2>
      <p id="ResumeParagraphs">
          This game was created for my C++ class with a partner. This was our first real experience making a program in a GUI.
          Because we both liked video games, we decided to try recreate the most simple game we could think of: Pong. 
          This project was developed in C++ on the 
          <a href="https://qt-project.org/">QTCreator</a>
           IDE.<br><br>
          
          Our version ofPong can be viewed on my bitbucket
          <a href="https://bitbucket.org/tawisler11/pong-project">Pong Project repository.</a>
      </p>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">Asteroids Game</h2>
      <p id="ResumeParagraphs">
          This project is a result of my passion for gaming. I have played video games for all my life, and I have always been interested in the actual
          development process. After I finally had the knowledge necessary to be able to create a basic game, I created my version of Asteroids. This was my
          first real attempt at making a game on my own. The game was designed fully in C++ and developed in the
          <a href="https://qt-project.org/">QTCreator</a>
           IDE.<br><br>
          The whole project including the code and images can be viewed on my bitbucket
          <a href="https://bitbucket.org/tawisler11/light_organ">Asteroids repository.</a>
      </p>
      
      <iframe width="560" height="315" src="https://www.youtube.com/embed/_20ZIM6FGdk" frameborder="0" allowfullscreen></iframe>
      
  </div>
  
  <div id="Projects" class="center jumbotron">
      
      <h2 id="ProjectTitles">"Bounce" Android Game</h2>
      <p id="ResumeParagraphs">
          This is another one of my personal projects that I began working on because I love gaming, and was interested in being able to develop Android applications.
          This game is a simple platform climbing type game, where the ball bounces higher when it hits a platform, pushing up the screen when it reaches the top.
          I developed this game in the 
          <a href="https://www.eclipse.org/">Eclipse</a>
           IDE.<br><br>
          The whole project including the code and images can be viewed on my bitbucket
          <a href="https://bitbucket.org/tawisler11/bounce/">Bounce repository.</a>
      </p>
      
  </div>
  
  
</div>

app/views/static_pages/resume.html.erb
<% provide(:title, "Resume") %>
<div class="center jumbotron">

<% link_to 'Click to download Word Document of Resume', "ResumeInternetVersion.doc" %>

  <h1>Resume</h1>
  
  <div id="Resume">
  
      <h2 id="ResumeTitles">objective:</h2>
      <p id="ResumeParagraphs">To obtain a computer engineering job utilizing my strong work ethic, and electrical/programming experience.</p><br>
      
      <h2 id="ResumeTitles">education:</h2>
      <p id="ResumeParagraphs">
      Trine University; Angola, IN</p>
      <p id="alignLeft">Bachelor of Science in <b>Computer Engineering</b></p>                                 <p id="alignRight">Anticipated Graduation: May 2015</p><br>
      <div style="clear: both;"></div>
      <p id="ResumeParagraphs"><b>GPA: 3.385 (4.0)</b></p><br>
      
      <h2 id="ResumeTitles">relevant coursework:</h2>
      <p id="ResumeParagraphs">
      Microcontrollers * Embedded Systems * C++ & Object Oriented Design * Object-Oriented Java Programming * Analog Signals * Discrete Electronics * Circuit Analysis * Digital Systems * 
      Computer Logic & Design * CMOS VLSI Design * Software Engineering * Computer Security</p><br>
      
      <h2 id="ResumeTitles">projects:</h2>
      <p id="ResumeParagraphs">
      Stopwatch – Start, stop, and reset buttons. Programmed in Verilog.<br>
      Tachometer – Calculated speed of a spinning wheel and displayed with 5x7 LED Matrix.<br>
      Light Organ – Personal project that changes LED strip colors to music.<br>
      3D TicTacToe Game – 3 player game, transmitting data over the network using QT GUI in C++.<br>
      Zen Alarm Clock – Progressive sound and light over time . Created Queues, Tasks, and Soft timers.</p><br>
      
      <h2 id="ResumeTitles">skills:</h2>
      <p id="ResumeParagraphs">
      <ul id="ResumeParagraphs">
          <li><b>Programming:</b> C, C#, C++, Assembly, Java (Android), Verilog, Python, Ruby on Rails, html/css</li>
          <li><b>Field Related:</b> Soldering, crimping</li>
          <li><b>Field Related Software:</b> Quartus II, Tina, Mathcad, AutoCAD, QT Creator, Netbeans, IAR Workbench, Eclipse, Arduino, Wireshark; Microsoft: Excel, PowerPoint, Word, Publisher, Visio</li>
      </ul>
      </p><br>
      
      
      <h2 id="ResumeTitles">experience:</h2>
      <p id="alignLeft">United Technologies Aerospace Systems; Raleigh, NC</p>                                 <p id="alignRight">05/2014-08/2014</p><br>
      <div style="clear: both;"></div>
      <p id="ResumeParagraphs">
      <b>Embedded Engineering Intern</b>
      <ul id="ResumeParagraphs">
          <li>Testing / Troubleshooting fully operational embedded PCB boards.</li>
          <li>Writing and fixing test procedure documentation.</li>
      </ul> </p> <br>
      
      <p id="alignLeft">Trine University; Angola, IN</p>                                 <p id="alignRight">01/2014-12/2014</p><br>
      <div style="clear: both;"></div>
      <p id="ResumeParagraphs">
      <b>Microcontrollers / Digital Systems Lab Assistant</b>
      <ul id="ResumeParagraphs">
          <li>Assist professor in teaching the Microcontrollers / Digital Systems class laboratory.</li>
          <li>Help students with any issues or questions they have during the laboratory.</li>
      </ul> </p> <br>
      
      <p id="alignLeft">Logikos, Fort Wayne, IN</p>                                 <p id="alignRight">05/2013-08/2013</p><br>
      <div style="clear: both;"></div>
      <p id="ResumeParagraphs">
      <b>Software Engineer Summer Intern</b>
      <ul id="ResumeParagraphs">
          <li>Working on RFID soda machine system with other interns and new engineers.</li>
          <li>Writing scripts, unit tests, debugging various types of software, fixing parts, and soldering.</li>
      </ul> </p> <br>
      
      <h2 id="ResumeTitles">activities/honors:</h2>
      <p id="ResumeParagraphs">
      <ul id="ResumeParagraphs">
          <li>Systems chair, Public relations chair, Steward, and Historian of the Delta Chi Fraternity</li>
          <li>Phi Eta Sigma National Freshman Honor Society 2012</li>
          <li>Dean’s List – Fall 2011, Spring 2012, Fall 2012, Fall 2013</li>
          <li>Wrestling: Team Captain; Team State Champions 2008, 2010; Individual Placer 8th 2010, 6th 2011</li>
          <li>Friendship Delegate to Shiojiri, Japan, Summer 2010</li>
      </ul>
      </p><br>
      
  </div>
  
</div>